version: "3.9"

services:
  web:
    image: corsicanec82/repl:latest
    environment:
      - SECRET_KEY_BASE
      - RAILS_SERVE_STATIC_FILES
    command: make start-production

  caddy:
    image: caddy:2.5.1
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
