version: "3.9"

services:
  web:
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      target: cached
    image: corsicanec82/repl:cached
    volumes:
      - .:/app
    command: make start

  frontend:
    image: corsicanec82/repl:cached
    volumes:
      - .:/app
    command: make start-frontend

  caddy:
    image: caddy:2.5.1
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
