services:
  app:
    build:
      args:
        - UID=1000
        - GID=1000
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: make start

  frontend:
    image: corsicanec82/repl:cached
    volumes:
      - .:/app
    command: make start-frontend
