version: "3.9"

services:
  app:
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      target: cached
    image: corsicanec82/repl:cached
    volumes:
      - .:/app
    ports:
      - ${PORT}:3000
    command: make start

  frontend:
    image: corsicanec82/repl:cached
    volumes:
      - .:/app
    command: make start-frontend
