name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build cached
        run: docker compose build app

      - name: Push cached
        run: docker compose push app

      - name: Build latest
        run: docker compose -f docker-compose.yml build app

      - name: Run checks
        run: docker compose -f docker-compose.yml up --abort-on-container-exit

      - name: Push latest
        run: docker compose -f docker-compose.yml push app
        if: ${{ github.event_name == 'push' }}
