name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push cached image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: cached
          cache-from: corsicanec82/repl:cached
          cache-to: type=inline
          tags: corsicanec82/repl:cached
          push: true

      - name: build latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: latest
          cache-from: corsicanec82/repl:cached
          cache-to: type=inline
          tags: corsicanec82/repl:latest

      - name: Run checks
        run: docker compose -f docker-compose.yml up --abort-on-container-exit

      - name: Push latest
        run: docker push corsicanec82/repl:latest
        if: ${{ github.event_name == 'push' }}
