name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker compose -f docker-compose.yml build

      - name: Run checks
        run: docker compose -f docker-compose.yml up --abort-on-container-exit

      - name: Push
        run: docker compose -f docker-compose.yml push app
        if: ${{ github.event_name == 'push' }}
